### ISSUE TITLE
Création du composant Background Pop-Up

### ISSUE THREAD

**Issue by Alakazouu** [jajanel/tp1-react-jb-ml#8]
Créer un composant qui contient le <div> qui va contenir les statistiques, descriptions et critiques
(background blanc avec un X pour la fermer)

**Comment by jajanel** [comment]
Il faut utiliser un modal de boostrap className="modal" permet de faire un "popup" avec un bouton X pour fermer. Voir: _https://getbootstrap.com/docs/4.0/components/modal/_

**Comment by jajanel** [comment]
Après réflexion, plus besoin de ce component.
